services:
  - type: web
    name: techvault-store
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        value: akilajonas001@gmail.com
      - key: EMAIL_PASS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
